### PR TITLE
Use Zstd_jll to provide zstd, update to 1.4.4

### LINKED ISSUE #17: Performance CodecZstd vs CodecZlib
Hi,

I am trying to compare `ZstdDecompressorStream`  with `GzipDecompressorStream`.
Let's consider a dataframe with two random float columns, compressed using zstd and gzip.

> 973M stats.csv
> 423M stats.csv.gz
> 448M stats.csv.zst

ZStd uncompress faster:

- 5.519s for `time zcat stats.csv.gz > /dev/null`

- 1.754s for `time zstdcat stats.csv.zst > /dev/null`

In Julia, I use the following to load the dataframe (taken from [here](https://stackoverflow.com/questions/52590792/how-do-i-read-a-gzipped-csv-file-in-julia)):

```
using CodecZstd, CodecZlib, CSVFiles, DataFrames, FileIO

function loader(file_name, decompressor)
  open(file_name) do io
    load(Stream(format"CSV", decompressor(io))) |> DataFrame
  end
end
```

With that code, I consistently get the following results:
```
julia> @time DataFrame(load("stats.csv"));
  2.425661 seconds (534 allocations: 1.002 GiB, 3.74% gc time)

julia> @time loader("stats.csv.gz", GzipDecompressorStream);
 10.230154 seconds (249.48 k allocations: 2.082 GiB, 1.71% gc time)

julia> @time loader("stats.csv.zst", ZstdDecompressorStream);
 16.919650 seconds (62.90 k allocations: 2.079 GiB, 1.15% gc time)

```
I am surprised to see that `ZstdDecompressorStream` is slower despite the gains seen above in decompression.

Are those results expected for the following versions of the packages?
```
(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [5d742f6a] CSVFiles v0.15.0
  [944b1d66] CodecZlib v0.6.0
  [6b39b394] CodecZstd v0.6.1
  [a93c6f00] DataFrames v0.19.2
  [5789e2e9] FileIO v1.0.7
```
```
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### LINKED ISSUE #19: slower than expected decompression, round 2
Spiritual successor to #13; not sure what the culprit is this time:

```
julia> using CodecZstd, TranscodingStreams

julia> bytes = read("fid_1509_2018_LTM.edf.zst");

julia> @time transcode(ZstdDecompressor, bytes);
 27.252612 seconds (594.62 k allocations: 1.858 GiB, 0.02% gc time)
``` 

```
>>> import zstandard as zstd
>>> import timeit
>>> byts = open('fid_1509_2018_LTM.edf.zst', 'rb').read();
>>> d = zstd.ZstdDecompressor()
>>> timeit.timeit("d.decompress(byts)", number=1, globals=globals())
3.793142723850906
```

### PR DESCRIPTION
**Pull request by ararslan**
This rips out the BinaryProvider machinery in favor of the JLL produced automatically by Yggdrasil. See [this blog post](https://julialang.org/blog/2019/11/artifacts/) for more information about JLLs. In doing this, it updates the version of zstd used to 1.4.4, as that's the latest version provided by Yggdrasil.

It seems that #19 and perhaps #17 as well were caused by an upstream performance regression. I haven't identified the exact upstream commit, but there was at least one known regression in zstd 1.4.2 that has since been fixed.

For a 3.4 MB zstd-compressed file, these are the timings I get. Setup code:
```julia
julia> using CodecZstd, TranscodingStreams

julia> bytes = read("file.zst");

julia> @time transcode(ZstdDecompress, bytes);
```
Output on CodecZstd v0.6.0:
```
  0.217029 seconds (594.58 k allocations: 34.930 MiB, 2.86% gc time)
```
CodecZstd v0.6.1:
```
  0.291829 seconds (594.58 k allocations: 34.930 MiB, 2.06% gc time)
```
This PR:
```
  0.218454 seconds (594.54 k allocations: 34.918 MiB)
```
Fixes #17, fixes #19 (would be good to have @jrevels and @Ankur-deDev confirm)

### CODE REVIEW

**Comment by ararslan** [comment]
Oh right, I forgot that JLLs only support Julia 1.3 and later... @bicycle1885, what are your thoughts on setting the minimum Julia version here to 1.3?

**Comment by ararslan** [comment]
I pushed a separate commit that bumps the package version and the minimum Julia version, since that's effectively required for this PR.

**Comment by jrevels** [comment]
Can confirm this substantially helps for #19! On this branch, I get: 

```
julia> @time transcode(ZstdDecompressor, bytes);
  3.925222 seconds (13 allocations: 1.830 GiB, 0.03% gc time)
```

But still seems to be slower than v0.6.0 by a tad (not horrible, but non-negligible):

```
julia> @time transcode(ZstdDecompressor, bytes);
  3.496933 seconds (13 allocations: 1.830 GiB, 0.60% gc time)
```

I guess this remaining chunk is probably another upstream perf issue?

**Comment by ararslan** [comment]
> I guess this remaining chunk is probably another upstream perf issue?

Absent testing directly with the C library, that would be my guess, since there haven't been any changes to the code here.

**Comment by Ankur-deDev** [comment]
Thanks for taking time to fix this! I have similar numbers.

CodecZstd v0.6.0:
`2.716708 seconds (17.69 M allocations: 5.577 GiB, 35.01% gc time)
`

CodecZstd v0.6.1:
`3.957340 seconds (17.69 M allocations: 5.577 GiB, 25.83% gc time)
`

PR#20:
`2.755108 seconds (17.69 M allocations: 5.577 GiB, 35.80% gc time)`

**Comment by bicycle1885** [comment]
Thank you very much for doing it.

> Oh right, I forgot that JLLs only support Julia 1.3 and later... @bicycle1885, what are your thoughts on setting the minimum Julia version here to 1.3?

I'm perfectly fine with it. People should always use the latest release of Julia 😄

I quickly benchmarked the performance using 80 MB compressed text. On my laptop (macOS), this pull request was significantly faster than v0.6.0 and v0.6.1. However, on a Linux machine, this was somewhat slower than v0.6.0 and v0.6.1. Strangely, I couldn't detect reported performance degradation on v0.6.1 (I ran Pkg.resolve and Pkg.build before each benchmarking, so I believe I used the correct target binaries). I'll take more time on diagnosis.

## macOS

v0.6.0:
```
  minimum time:     797.550 ms (0.03% GC)
  median time:      817.193 ms (3.74% GC)
  mean time:        822.142 ms (4.90% GC)
  maximum time:     866.895 ms (9.58% GC)
```

v0.6.1 (master):
```
  minimum time:     757.091 ms (0.03% GC)
  median time:      807.879 ms (3.43% GC)
  mean time:        811.865 ms (4.83% GC)
  maximum time:     870.128 ms (9.86% GC)
```

PR#20:
```
  minimum time:     692.454 ms (3.96% GC)
  median time:      717.373 ms (3.86% GC)
  mean time:        723.640 ms (5.46% GC)
  maximum time:     774.395 ms (10.65% GC)
```

## Linux (x86-64)

v0.6.0:
```
  minimum time:     494.814 ms (0.36% GC)
  median time:      501.083 ms (0.36% GC)
  mean time:        516.164 ms (3.79% GC)
  maximum time:     578.022 ms (14.15% GC)
```

v0.6.1 (master):
```
  minimum time:     499.878 ms (0.07% GC)
  median time:      502.071 ms (0.37% GC)
  mean time:        517.356 ms (3.38% GC)
  maximum time:     581.141 ms (13.92% GC)
```

PR#20:
```
  minimum time:     554.353 ms (0.05% GC)
  median time:      558.730 ms (0.32% GC)
  mean time:        571.599 ms (2.74% GC)
  maximum time:     630.729 ms (11.83% GC)
```

**Comment by ararslan** [comment]
Interesting. The timings I reported in the PR body, where the performance was 0.6.1 < this PR < 0.6.0 were from x64 Linux as well.

**Comment by jrevels** [comment]
Would love if this were merged/tagged soon :) seems like a straight win to at least upgrade to the new Artifact system for the underlying zstd binary (even if zstd itself seems to have some perf fluctuations)

**Comment by ararslan** [comment]
As Jarrett said, I think this PR provides a strict improvement in terms of quality of life for recent Julia versions. Given that there seem to be performance fluctuations in zstd itself and this PR is otherwise a non-functional change, I think we should just go ahead and merge it.

**Pull request merged**
